server:
  port: 8081
  servlet:
    context-path: /
spring:
  application:
    name: dubbo-samples-provider
dubbo:
  application:
    id: dubbo-samples-provider
    name: dubbo-samples-provider
  registry:
    address: zookeeper://8.131.87.108:2181
    timeout: 25000
  protocol:
    name: dubbo
    port: 20881
  provider:
    token: true
  monitor:
    protocol: registry