server:
  port: 8080

dubbo:
  application:
    name:dubbo-samples-consumer
  registry:
    address:zookeeper://8.131.87.108:2181
  protocol:
    name: dubbo
    port: 20880
    scan: com.mangxiao.samples.dubbo.provider.service.impl