server:
  port: 8085
  servlet:
    context-path: /
spring:
  application:
    name: dubbo-samples-providerx
dubbo:
  application:
    id: dubbo-samples-providerx
    name: dubbo-samples-providerx
  registry:
    address: zookeeper://8.131.87.108:2181
    timeout: 25000
  protocol:
    port: 8099
    name: hessian
    server: jetty
  provider:
    token: true
  monitor:
    protocol: registry