server:
  port: 8085
  servlet:
    context-path: /
spring:
  application:
    name: hessian-samples-provider
dubbo:
  application:
    id: hessian-samples-provider
    name: hessian-samples-provider
  registry:
    address: zookeeper://8.131.87.108:2181
    timeout: 25000
    id: studentRegistry
  protocol:
    port: 8099
    name: hessian
    server: servlet
  provider:
    token: false
    protocol: hessian
  monitor:
    protocol: registry